---
# Options for all commands
position: before
position_in_additional_file_patterns: before
position_in_class: before
position_in_factory: before
position_in_fixture: before
position_in_test: before
position_in_routes: before
position_in_serializer: before

# Options for models
classified_sort: false
format_markdown: false
format_rdoc: false
format_yard: false
force: true
frozen: false
ignore_columns: null
ignore_routes: null
ignore_unknown_models: false
include_version: false
mark_routes: false
model_dir: app/models
require: []
root_dir: []
show_check_constraints: false
show_complete_foreign_keys: false
show_foreign_keys: true
show_indexes: true
simple_indexes: false
sort_columns: true
timestamp: false
trace: false
with_column_comments: true
with_comment: true
with_table_comments: true
